ALTER TABLE ORDERLINE ADD CONSTRAINT FK_ORDERLINE_OWNING_ORDER_ID FOREIGN KEY (OWNING_ORDER_ID) REFERENCES ORDER_TBL (ORDER_ID);
ALTER TABLE ORDERLINE ADD CONSTRAINT FK_ORDERLINE_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID);
ALTER TABLE ORDER_TBL ADD CONSTRAINT FK_ORDER_TBL_OWNING_CUST_ID FOREIGN KEY (OWNING_CUST_ID) REFERENCES CUSTOMER (ID);
ALTER TABLE CUSTOMER ADD CONSTRAINT FK_CUSTOMER_BILLING_ADDR FOREIGN KEY (BILLING_ADDR) REFERENCES CUST_ADDR (ADDR_ID);
ALTER TABLE CUSTOMER ADD CONSTRAINT FK_CUSTOMER_SHIPPING_ADDR FOREIGN KEY (SHIPPING_ADDR) REFERENCES CUST_ADDR (ADDR_ID);
ALTER TABLE STORES_PRODUCTS ADD CONSTRAINT FK_STORES_PRODUCTS_STORE_ID FOREIGN KEY (STORE_ID) REFERENCES STORES (STORE_ID);
ALTER TABLE STORES_PRODUCTS ADD CONSTRAINT FK_STORES_PRODUCTS_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID);